dresser/dresser/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'products.views.home', name='home'),
    url(r'^s/$', 'products.views.search', name='search'),
    url(r'^products/$', 'products.views.all', name='products'),
    url(r'^products/(?P<slug>[\w-]+)/$', 'products.views.single', name='single_product'),

    url(r'^products/sales/sale$', 'products.views.sales_view', name='sales'),

    # the part of the urls will need to modified by passing the category id or brand id
    # to the corresponding view
    url(r'^products/categorys/shirts/$', 'products.views.shirts_category', name='shirts_category'),
    url(r'^products/categorys/jeans/$', 'products.views.jeans_category', name='jeans_category'),
    url(r'^products/categorys/tees/$', 'products.views.tees_category', name='tees_category'),
    url(r'^products/categorys/suits/$', 'products.views.suits_category', name='suits_category'),
    url(r'^products/categorys/hoodies/$', 'products.views.hoodies_category', name='hoodies_category'),
    url(r'^products/categorys/shoes/$', 'products.views.shoes_category', name='shoes_category'),
    url(r'^products/categorys/jackets/$', 'products.views.jackets_category', name='jackets_category'),

    url(r'^products/brands/zara/$', 'products.views.zara', name='zara'),
    url(r'^products/brands/northface/$', 'products.views.northface', name='northface'),
    url(r'^products/brands/jcrew/$', 'products.views.jcrew', name='jcrew'),
    url(r'^products/brands/nike/$', 'products.views.nike', name='nike'),
    url(r'^products/brands/topshop/$', 'products.views.topshop', name='topshop'),
    url(r'^products/brands/allsaints/$', 'products.views.allsaints', name='allsaints'),
    url(r'^products/brands/h_m/$', 'products.views.h_m', name='h_m'),
    

    url(r'^cart/(?P<id>\d+)/$', 'carts.views.remove_from_cart', name='remove_from_cart'),
    url(r'^cart/(?P<slug>[\w-]+)/$', 'carts.views.add_to_cart', name='add_to_cart'),
    url(r'^cart/$', 'carts.views.view', name='cart'),

    url(r'^checkout/$', 'orders.views.checkout', name='checkout'),
    url(r'^orders/(?P<id>\d+)/$', 'orders.views.order_detail', name='order_detail'),
    url(r'^orders/$', 'orders.views.orders', name='user_orders'),

    url(r'^ajax/add_user_address/$', 'accounts.views.add_user_address', name='ajax_add_user_address'),

    #(?P<all_items>.*)
    #(?P<id>\d+)
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/logout/$', 'accounts.views.logout_view', name='auth_logout'),
    url(r'^accounts/login/$', 'accounts.views.login_view', name='auth_login'),
    url(r'^accounts/register/$', 'accounts.views.registration_view', name='auth_register'),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', 'accounts.views.activation_view', name='activation_view'),
    url(r'^accounts/profile/$', 'accounts.views.profile_view', name='my_profile'),
) 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dresser/orders/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.conf import settings
# Create your models here.
from carts.models import Cart


STATUS_CHOICES = (
		("Started", "Started"),
		("Shipped", "Shipped"),
		("Finished", "Finished"),
	)

#python tuples

User = get_user_model()

class Order(models.Model):
	user = models.ForeignKey(User, blank=True, null=True)
	order_id = models.CharField(max_length=50, default='ABC', unique=True)
	cart = models.ForeignKey(Cart)
	status = models.CharField(max_length=50, choices=STATUS_CHOICES, default="Started")
	# address **
	sub_total = models.DecimalField(default=10.99, max_digits=50, decimal_places=2)
	tax_total = models.DecimalField(default=0.00, max_digits=50, decimal_places=2)
	final_total = models.DecimalField(default=10.99, max_digits=50, decimal_places=2)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __unicode__(self):
		return self.order_id

	def get_final_amount(self):
		instance = Order.objects.get(id=self.id)
		instance.tax_total = 0.08 * float(self.sub_total)
		instance.final_total = float(self.sub_total) + float(instance.tax_total)
		instance.save()
		return instance.final_total

dresser/orders/views.py
import time

import stripe

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, HttpResponseRedirect

# Create your views here.

from accounts.forms import UserAddressForm
from accounts.models import UserAddress
from carts.models import Cart

from .models import Order
from .utils import id_generator

try:
	stripe_pub = settings.STRIPE_PUBLISHABLE_KEY
	stripe_secret = settings.STRIPE_SECRET_KEY
except Exception, e:
	print str(e)
	raise NotImplementedError(str(e))


stripe.api_key = stripe_secret


def orders(request):
	context = {}
	template = "orders/user_orders.html"
	return render(request, template, context)


def order_detail(request, id):
	try:
		order = Order.objects.get(id=id)
	except:
		order = None
	context = {"order": order}
	template = "orders/order_detail.html"
	return render(request, template, context)

#require user login ** 
@login_required
def checkout(request):
	try:
		the_id = request.session['cart_id']
		cart = Cart.objects.get(id=the_id)
	except:
		the_id = None
		#return HttpResponseRedirect("/cart/")
		return HttpResponseRedirect(reverse("cart"))
	
	try:
		new_order = Order.objects.get(cart=cart)
	except Order.DoesNotExist:
		new_order = Order()
		new_order.cart = cart
		new_order.user = request.user
		new_order.order_id = id_generator()
		new_order.save()
	except:
		new_order = None
		# work on some error message
		return HttpResponseRedirect(reverse("cart"))
	final_amount = 0
	if new_order is not None:
		new_order.sub_total = cart.total
		new_order.save()
		final_amount = new_order.get_final_amount()

	try:
		address_added = request.GET.get("address_added")
	except:
		address_added = None

	if address_added is None:
		address_form = UserAddressForm()
	else:
		address_form = None

	current_addresses = UserAddress.objects.filter(user=request.user)
	billing_addresses = UserAddress.objects.get_billing_addresses(user=request.user)
	print billing_addresses
	##1 add shipping address
	##2 add billing address
	#3 add and run credit card 

	if request.method == "POST":
		try:
			user_stripe = request.user.userstripe.stripe_id
			customer = stripe.Customer.retrieve(user_stripe)
			print customer
		except:
			customer = None
			pass
		if customer is not None:
			token = request.POST['stripeToken']
			card = customer.sources.create(card=token)
			charge = stripe.Charge.create(
				  amount= int(final_amount * 100),
				  currency="usd",
				  card = card, # obtained with Stripe.js
				  customer = customer,
				  description="Charge for %s" %(request.user.username)
				)
			if charge["captured"]:
				new_order.status = "Finished"
				new_order.save()
				del request.session['cart_id']
				del request.session['items_total']
				messages.success(request, "Thank your order. It has been completed!")
				return HttpResponseRedirect(reverse("user_orders"))

	context = {
	"order": new_order,
	"address_form": address_form,
	"current_addresses": current_addresses,
	"billing_addresses": billing_addresses,
	"stripe_pub": stripe_pub,
	}
	template = "orders/checkout.html"
	return render(request, template, context)

dresser/templates/orders/checkout.html
{% extends "base.html" %}

<script>
{% block jquery %}
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('{{ stripe_pub }}');
jQuery(function($) {
  $('#payment-form').submit(function(event) {
    var $form = $(this);
    // Disable the submit button to prevent repeated clicks
    $form.find('button').prop('disabled', true);
    Stripe.card.createToken($form, stripeResponseHandler);
    // Prevent the form from submitting with the default action
    return false;
  });
});
function stripeResponseHandler(status, response) {
  var $form = $('#payment-form');
  if (response.error) {
    // Show the errors on the form
    $form.find('.payment-errors').text(response.error.message);
    $form.find('button').prop('disabled', false);
  } else {
    // response contains id and card, which contains additional card details
    var token = response.id;
    // Insert the token into the form so it gets submitted to the server
    $form.append($('<input type="hidden" name="stripeToken" />').val(token));
    // and submit
    $form.get(0).submit();
  }
};
{% endblock %}
</script>

{% block content %}


{% if address_form %}
<div class='col-sm-6 pull-right'>
<h3>Add new Shipping Address</h3>
<form method="POST" action='{% url "ajax_add_user_address" %}?next=checkout'>{% csrf_token %}
{{ address_form.as_p }}

<input type='submit' class='btn btn-default' value='Add Shipping Address'/>
</form>
</div>
{% endif %}



<h1>Current total: {{ order.get_final_amount }}</h1>
<form method='POST' action="" id="payment-form"> {% csrf_token %}
{% if current_addresses  %}
<div class='col-sm-6'>
<h3>Shipping Addresses</h3>
{% for address in current_addresses %}

{% if request.user.userdefaultaddress.shipping.id == address.id %} 

<input type='radio' name='shipping_address' value='{{ address.id }}' checked='checked'/> {{ address.get_address }} <br/>
{% else %}
<input type='radio' name='shipping_address' value='{{ address.id }}' /> {{ address.get_address }} <br/>

{% endif %}

{% endfor %}
</div>
{% endif %}




<div class='row'>

{% if billing_addresses  %}
<div class='col-sm-6'>
<h3>Billing Addresses</h3>
{% for address in billing_addresses %}

{% if request.user.userdefaultaddress.billing.id == address.id %} 

<input type='radio' name='billing_address' value='{{ address.id }}' checked='checked'/> {{ address.get_address }} <br/>
{% else %}
<input type='radio' name='billing_address' value='{{ address.id }}' /> {{ address.get_address }} <br/>

{% endif %}

{% endfor %}
</div>
{% endif %}



</div>

<div class='row'>

<h3>Credit Card Info</h3>

  <span class="payment-errors"></span>

  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
      <input type="text" size="2" data-stripe="exp-month"/>
    </label>
    <span> / </span>
    <input type="text" size="4" data-stripe="exp-year"/>
  </div>

  <button type="submit">Submit Payment</button>




</div>

</form>

{% endblock %}

dresser/templates/orders/order_detail.html
{% extends "base.html" %}


{% block content %}
<!-- 
<div class='row'>
	<div class='col-sm-4'>

	
	</div>

</div> -->

<div class="row">
	  <div class="col-sm-4 col-md-4">
	    <div class="thumbnail">
	    	
	      <div class="caption">
	      	<h4>Order Date: {{ order.timestamp }}
	        <h4>Order ID: {{ order }}</h4>
	        <h4>Sub_Total: {{ order.sub_total }}</h4>
			<h4>Tax_Total: {{ order.tax_total }}</h4>
			<h4>Final_Total: {{ order.final_total }}</h4>
			<h4>Status: {{ order.status }}</h4>
	       
	      </div>
	    </div>
</div>



{% endblock %}

dresser/templates/orders/user_orders.html
{% extends "base.html" %}


{% block content %}

<div class='row'>
	<div class='col-sm-4'>

		<h1>{{ user }}'s order history</h1>
		</hr>
	
	</div>

</div>

<div class="row">
	{% for order in user.order_set.all %}
	  <div class="col-sm-4 col-md-4">
	    <div class="thumbnail">
	    	
	      <div class="caption">
	      	<h4>Order Date: {{ order.timestamp }}
			<h4>Final_Total: {{ order.final_total }}</h4>
			<h4>Status: {{ order.status }}</h4>
	        <p><a href='{% url "order_detail" order.id %}' class="btn btn-info" role="button">View Details</a>
	      </div>
	    </div>
	  </div>
	{% endfor %}
</div>



{% endblock %}